on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]

name: Main Workflow
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        pytest tests.py --cov=main --cov-report=xml:coverage.xml -v

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # Ex: v4.1.0 or sha1, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
